# Generated by Django 3.2.8 on 2023-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('0', 'Жеңіл автомобил'), ('1', 'Фургон'), ('2', 'Үлкен жүк көлік')], default='0', max_length=1, verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
