# Generated by Django 3.2.8 on 2023-10-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20231002_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applicable',
        ),
    ]
