# Generated by Django 3.2.8 on 2024-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='applicable',
            field=models.ManyToManyField(related_name='applicable', to='product.Category'),
        ),
    ]
