# Generated by Django 3.2.8 on 2023-10-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20231002_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(to='product.ProductGallery'),
        ),
    ]
