# Generated by Django 3.2.8 on 2024-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applicable',
        ),
        migrations.AddField(
            model_name='product',
            name='applicable',
            field=models.CharField(default='', max_length=254, verbose_name='适配的类型'),
            preserve_default=False,
        ),
    ]
