# Generated by Django 3.2.8 on 2024-04-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240414_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default=None, upload_to='product'),
            preserve_default=False,
        ),
    ]
