# Generated by Django 3.2.8 on 2023-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
