# Generated by Django 3.2.8 on 2023-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20231009_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to='product/%Y/%m/%d/'),
        ),
    ]
