# Generated by Django 3.2.8 on 2023-10-09 06:33

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to=product.models.wrapper),
        ),
    ]
