# Generated by Django 3.2.8 on 2023-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
