# Generated by Django 3.2.8 on 2023-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('fullname', models.CharField(max_length=30, verbose_name='全名')),
                ('password', models.CharField(max_length=254, verbose_name='密码')),
                ('role', models.CharField(choices=[('0', '提供者'), ('1', '消费者')], max_length=1, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'db_table': 'user',
            },
        ),
    ]
