# Generated by Django 3.2.8 on 2023-10-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
